stages:
- stage: PrepareArtifacts
  jobs:
    - job: Prep
      # Add/modify platforms by editing the matrix entries below.
      strategy:
        matrix:
          linux_amd64_ubuntu2204:
            PLATFORM: linux/amd64
            DISTRO: ubuntu
            VER: '22.04'
          linux_amd64_ubuntu2404:
            PLATFORM: linux/amd64
            DISTRO: ubuntu
            VER: '24.04'
          linux_arm64_ubuntu2404:
            PLATFORM: linux/arm64
            DISTRO: ubuntu
            VER: '24.04'
      pool:
        name: 'GenericPool'  # Apply tags in the matrix to specific agent with wanted platform
      steps:
        - script: |
            set -euo pipefail
            out_dir=./output/$(System.JobName)
            mkdir -p "$out_dir"
            source ./build.sh
            craft_platform_specific "$DISTRIBUTION_ROOT" "$out_dir"
            echo "Generated digest file: $out_dir/digest" >&2
          name: captureDigest
        - publish: ./output/$(System.JobName)
          artifact: $(System.JobName)

- stage: ProcessArtifacts
  dependsOn: PrepareArtifacts
  jobs:
    - job: Process
      pool:
        name: 'ProcessingHostPool'
      steps:
        - download: current
        - script: |
            set -euo pipefail
            out_dir=./output/$(System.JobName)
            mkdir -p "$out_dir"
            source ./build.sh
            craft_multi_platform_index "$(Pipeline.Workspace)" "$out_dir" "$VERSION"
          name: createIndex
        - publish: ./output/$(System.JobName)
          artifact: $(System.JobName)